add filter

diff --git a/.github/workflows/handle-discussions.yml b/.github/workflows/handle-discussions.yml
--- a/.github/workflows/handle-discussions.yml
+++ b/.github/workflows/handle-discussions.yml
@@ -8,6 +8,16 @@ jobs:
   handle-discussion:
     runs-on: ubuntu-22.04
     steps:
+      - name: Filter Discussion
+        run: |
+          echo "::group::Filter Discussion"
+          echo "discussion id ${{ github.event.discussion.node_id }} in category ${{ github.event.discussion.category.name }} ${{ github.event.discussion.category.node_id }}"
+          echo "::endgroup::"
+          if [ "${{ github.event.discussion.category.name }}" != "Announcements" ]; then
+            echo "Category does not match. Stopping the workflow."
+            exit 0
+          fi
+
       - name: Checkout the repository
         uses: actions/checkout@v4
 
@@ -17,14 +27,10 @@ jobs:
 
       - name: Update Github Discussions
         run: |
-          echo "Discussion with id ${{ github.event.discussion.node_id }} unlocked in category ${{ github.event.discussion.category.name }} ${{ github.event.discussion.category.node_id }}"
-
-          if [ "${{ github.event.discussion.category.name }}" == "Announcements" ]; then 
-            response=$(curl -i -H 'Content-Type: application/json' -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"query": "mutation {updateDiscussion(input: {discussionId: \"${{ github.event.discussion.node_id }}\", body: \"${{ steps.prepare-data.outputs.text }}\"}) {discussion { id } }}"}' https://api.github.com/graphql)
-            if echo "$response" | grep -q '"errors"'; then
-              echo "failed: $response"
-              exit 1
-            else 
-              echo "succes: $response"
-            fi
+          response=$(curl -i -H 'Content-Type: application/json' -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"query": "mutation {updateDiscussion(input: {discussionId: \"${{ github.event.discussion.node_id }}\", body: \"${{ steps.prepare-data.outputs.text }}\"}) {discussion { id } }}"}' https://api.github.com/graphql)
+          if echo "$response" | grep -q '"errors"'; then
+            echo "failed: $response"
+            exit 1
+          else 
+            echo "succes: $response"
           fi
